package com.rbs.predictor.ui.welcome
//package com.rbs.predictor
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.findNavController
import com.rbs.predictor.databinding.FragmentWelcomeBinding

// Fragment for the welcome screen
class WelcomeFragment : Fragment() {

    // View Binding
    private var _binding: FragmentWelcomeBinding? = null
    private val binding get() = _binding!!

    // create the view hierarchy
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        // Inflate the layout using View Binding
        _binding = FragmentWelcomeBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Set click listener for the "Go to Prediction" button
        binding.buttonGoToPrediction.setOnClickListener {
            // Navigate to the PredictionFragment using the action generated by Safe Args
            // WelcomeFragmentDirections.actionWelcomeFragmentToPredictionFragment() is generated
            findNavController().navigate(WelcomeFragmentDirections.actionWelcomeFragmentToPredictionFragment())
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null // Clean up the binding reference
    }
}
